version: '3'
services:
  hub:
    image: selenium/hub
    networks:
      - nightwatch-docker-grid-network
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 8000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 120000
    ports:
      - '4444:4444'
  node-chrome:
    image: selenium/node-chrome
    networks:
      - nightwatch-docker-grid-network
    environment: &SELENIUM_NODE_ENV
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    logging:
      driver: none
  e2e:
    container_name: e2e
    working_dir: /usr/myp2-frontend/e2e
    networks:
      - nightwatch-docker-grid-network
    environment:
      - UI_HOST=client
      - UI_PORT=3000
      - SELENIUM_PORT=4444
      - SELENIUM_HOST=chromedriver
      - SELENIUM_HUB=hub
      - DOCKER=true
      - WAIT_HOSTS= client:3000
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/myp2-frontend/e2e
      - /usr/myp2-frontend/e2e/node_modules
    command: |
      sh -c "/wait && sleep 5 && npm start"
networks:
  nightwatch-docker-grid-network:
    driver: bridge
